/*
 * uberapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/21/2016
 */

package apiclient_pkg

import "uberapi_lib/models_pkg"

/*
 * Interface for the APICLIENT_IMPL
 */
type APICLIENT interface {
    GetProductsTypes (*GetProductsTypesInput) (*models_pkg.ProductCollection, error)

    GetPriceEstimates (*GetPriceEstimatesInput) (*models_pkg.PriceEstimateCollection, error)

    GetTimeEstimates (*GetTimeEstimatesInput) (*models_pkg.TimeEstimateCollection, error)

    GetUserActivityV11 (*GetUserActivityV11Input) (*models_pkg.UserActivity, error)

    GetUserProfile () (*models_pkg.UserProfile, error)

    GetProductDetailByID (string) (*models_pkg.Product, error)

    GetPromotions (*GetPromotionsInput) (*models_pkg.PromotionsResponse, error)

    CreateRequest (*models_pkg.RequestBody) (*models_pkg.Request, error)

    GetRequestDetails (string) (*models_pkg.RequestDetailsCollections, error)

    DeleteRequestCancel (string) (error)

    GetRequestMap (string) (*models_pkg.RequestMapResponse, error)
}

/*
 * Factory for the APICLIENT interaface returning APICLIENT_IMPL
 */
func NewAPICLIENT() APICLIENT {
    return &APICLIENT_IMPL{}
}