/*
 * uberapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 on 05/21/2016
 */

package uberapi_lib

/** The base Uri for API calls */
const BASEURI string = "https://api.uber.com/v1"

var Config struct {
    /** The OAuth 2.0 access token to be set before API calls */
    /** Replace the value of OAuthAccessToken with an appropriate value */
    OAuthAccessToken string
}
